- name: Fetch facts from remote servers
  hosts: linux
  gather_facts: true
  tasks:
    - name: Fetch facts
      copy:
        src: "{{ ansible_facts }}"
        dest: "/opt/statebackup/facts/{{ ansible_date_time.date }}_{{ ansible_date_time.time }}_{{ inventory_hostname }}"
      delegate_to: localhost