---
- name: Install / Update Packages
  hosts: localhost
  become: true
  vars:
    package_names: "{{ package_to_install.split(',') }}"
  tasks:
    - name: Print a message
      debug:
        msg: "Hello, Ansible!"

- import_playbook: /opt/playbooks/addrepo.yaml
- import_playbook: /opt/playbooks/update_local_repo.yml
- import_playbook: /opt/playbooks/fetchfacts.yaml
- import_playbook: /opt/playbooks/remove_packages.yaml run_on=rsi{{scanner_no}},rre{{scanner_no}},tde{{scanner_no}}
- import_playbook: /opt/playbooks/install_packages.yaml run_on=rsi{{scanner_no}},rre{{scanner_no}},tde{{scanner_no}}
- import_playbook: /opt/playbooks/remove_packages.yaml run_on=rec{{scanner_no}}
- import_playbook: /opt/playbooks/install_packages.yaml run_on=rec{{scanner_no}}







