- hosts: all
  become: true

  tasks:
    - name: Install YUM packages
      delegate_to: localhost
      yum:
        name: "{{ packages }}"
        state: latest
      vars:
        packages: "{{ lookup('file', '/opt/playbooks/packages.txt').splitlines() }}"

