---
- name: Deploy packages to scanners
  hosts: scanner{{ scanner_number }}
  gather_facts: false


  tasks:
    - name: Filter hosts by group name
      set_fact:
        filtered_hosts: "{{ groups[group_name] if group_name != 'all' else groups.all }}"

    - name: Print filtered hosts
      debug:
        var: filtered_hosts

    - name: Remove the packages
      become: true
      yum:
        name: "{{ item }}"
        state: absent
      loop: "{{ package_names.split(',') }}"
      loop_control:
        loop_var: item
      when: inventory_hostname in filtered_hosts

    - name: Install the packages
      become: true
      yum:
        name: "{{ item }}"
        state: present
      loop: "{{ package_names.split(',') }}"
      loop_control:
        loop_var: item
      when: inventory_hostname in filtered_hosts
