---
- name: Install NVIDIA Driver
  hosts: rre{{ scanner_number }}
  become: true

  vars:
    major_version: 1
    minor_version: 0
    tick_version: 4
    log_directory: /var/rtt/log
    logfile: "{{ log_directory }}/{{ inventory_hostname }}.{{ ansible_date_time.date }}.log"
    rpms_installing: NVIDIA-440.44

  tasks:
    - name: Make sure log directory exists
      file:
        path: "{{ log_directory }}"
        state: directory
        mode: "0755"
        owner: rtt
        group: rtt

- name: Install required packages and NVIDIA driver
  hosts: rre{{ scanner_number }}
  become: true
  tasks:
    - name: Install required packages
      yum:
        name:
          - kernel-devel
          - gcc
          - kernel-headers
          - make
        state: present

    - name: Set execute permissions on the script
      delegate_to: localhost
      file:
        path: /opt/playbooks/NVIDIA-Linux-x86_64-440.44-no-compat32.run
        mode: '0755'

    - name: Install NVIDIA Driver
      become: true
      command: "/opt/playbooks/NVIDIA-Linux-x86_64-440.44-no-compat32.run --no-opengl-files --no-questions --ui=none --accept-license"
      args:
        chdir: "/tmp"

    - name: Reboot the system
      command: "reboot"
      async: 0
      poll: 0

