---
- name: Removing the package after reading from file
  hosts: "{{ group_name }}"
  gather_facts: true
  become: true
  vars:
    default_package_file: "/home/repos/packages/packages.txt"
    package_file: "{{ package_path | default(default_package_file) }}"

  tasks:
    - name: Backup Packages State before Change
      package_facts:
        manager: auto
      register: package_facts_result
      ignore_errors: true

    - name: Backup Packages State before Change (Step 2)
      template:
        src: soft_facts.j2
        dest: "/opt/statebackup/software/deploy_pkg_single_grp_before_using_file{{ ansible_date_time.date }}_{{ ansible_date_time.time }}_{{ inventory_hostname }}"
      delegate_to: localhost
      ignore_errors: true

    - name: Read package names from the file
      set_fact:
        package_names: "{{ lookup('file', package_file).splitlines() }}"

    - name: Remove the packages
      become: true
      yum:
        name: "{{ item }}"
        state: absent
      loop: "{{ package_names }}"
      loop_control:
        loop_var: item

    - name: Install the  packages
      become: true
      yum:
        name: "{{ item }}"
        state: present
      loop: "{{ package_names }}"
      loop_control:
        loop_var: item

    - name: Backup Packages State after Change
      package_facts:
        manager: auto
      register: package_facts_result
      ignore_errors: true


    - name: Backup Packages State after Change (Step 2)
      template:
        src: soft_facts.j2
        dest: "/opt/statebackup/software/deploy_pkg_single_grp_after_using_file{{ ansible_date_time.date }}_{{ ansible_date_time.time }}_{{ inventory_hostname }}"
      delegate_to: localhost
      ignore_errors: true
