---
- name: Install NVIDIA Driver
  hosts: "{{ scanner }}"
  become: true
  become_user: root

  vars:
    major_version: 1
    minor_version: 0
    tick_version: 4
    log_directory: /var/rtt/log
    logfile: "{{ log_directory }}/{{ inventory_hostname }}.{{ ansible_date_time.date }}.log"
    kernel_releases:
      - 3.10.0-1160.76.1.el7.x86_64
    centos_releases:
      - 7.9
    rpms_installing: NVIDIA-440.44

  tasks:
    - name: Make sure log directory exists
      file:
        path: "{{ log_directory }}"
        state: directory
        mode: "0755"
        owner: rtt
        group: rtt

    - name: Check OS and kernel release
      block:
        - name: Check kernel release
          fail:
            msg: "Kernel release {{ ansible_kernel }} not supported. Supported releases: {{ kernel_releases }}"
          when: ansible_kernel not in kernel_releases

    - name: Install required packages
      yum:
        name:
          - kernel-devel
          - gcc
          - kernel-headers
          - make
        state: present
      delegate_to: "{{ groups[group_name][0] }}"

    - name: Set execute permissions on the script
      delegate_to: localhost
      file:
        path: /opt/playbooks/NVIDIA-Linux-x86_64-440.44-no-compat32.run
        mode: '0755'

    - name: Install NVIDIA Driver
      delegate_to: localhost
      become: true
      become_user: root
      command: "/opt/playbooks/NVIDIA-Linux-x86_64-440.44-no-compat32.run --no-opengl-files --no-questions --ui=none --accept-license"
      args:
        chdir: "/tmp"

    - name: Reboot the system
      command: "reboot"
      async: 0
      poll: 0
      when: ansible_distribution_major_version == "7"

