---
- name: Deploy packages to scanners
  hosts: scanner{{ scanner_number }}
  gather_facts: false

  tasks:
    - name: Filter hosts by group name
      set_fact:
        filtered_hosts: "{{ groups[group_name] if group_name != 'all' else groups.all }}"

    - name: Read package names from the file
      delegate_to: localhost
      set_fact:
        package_names: "{{ lookup('file', '/opt/playbooks/rpm_lists/packages.txt').splitlines() }}"

    - name: Remove the packages
      become: true
      yum:
        name: "{{ item }}"
        state: absent
      loop: "{{ package_names }}"
      loop_control:
        loop_var: item
      when: inventory_hostname in filtered_hosts

    - name: Install the  packages
      become: true
      yum:
        name: "{{ item }}"
        state: present
      loop: "{{ package_names }}"
      loop_control:
        loop_var: item
      when: inventory_hostname in filtered_hosts
