---
- name: Install Packages
  hosts: your_target_hosts
  become: true
  vars:
    package_names: "{{ package_to_install.split(',') }}"
  tasks:
    - name: Install the packages
      yum:
        name: "{{ item }}"
        state: present
      loop: "{{ package_names }}"
      loop_control:
        loop_var: item
        