---
- name: Install software on the target hosts
  hosts: "{{ scanner }}"
  become: true

  tasks:
    - name: Read package names from the file
      delegate_to: localhost
      set_fact:
        package_names: "{{ lookup('file', '/opt/playbooks/rpm_lists/packages.txt').splitlines() }}"

    - name: Check if the current host is the target host
      block:
        - debug:
            msg: "This is the target host. Installing software..."
          when: inventory_hostname in groups[group]  # Check if the current host is in the specified group for the scanner

        - debug:
            msg: "This is not the target host. Skipping software installation."
          when: inventory_hostname not in groups[group]  # Check if the current host is not in the specified group for the scanner

    - name: Install software
      block:
        - name: Install the required packages
          yum:
            name: "{{ package_names }}"
            state: present
          when:
            - inventory_hostname in groups[group]  # Check if the current host is in the specified group for the scanner
            - package_names is defined and package_names | length > 0  # Check if the package names are defined and not empty

