---
- name: Deploy packages to groups
  hosts: "{{ group_name }}"
  gather_facts: true


  tasks:
    - name: Backup Packager State before Change
      package_facts:
        manager: auto
      register: package_facts_result
      ignore_errors: true

    - name: Backup Packager State before Change (Step 2)
      template:
        src: soft_facts.j2
        dest: "/opt/statebackup/software/deploy_pkg_single_grp_before_{{ ansible_date_time.date }}_{{ ansible_date_time.time }}_{{ inventory_hostname }}"
      delegate_to: localhost
      ignore_errors: true



    - name: Remove the packages
      become: true
      yum:
        name: "{{ item }}"
        state: absent
      loop: "{{ package_names.split(',') }}"
      loop_control:
        loop_var: item

    - name: Install the packages
      become: true
      yum:
        name: "{{ item }}"
        state: present
      loop: "{{ package_names.split(',') }}"
      loop_control:
        loop_var: item

    - name: Backup Packager State after Change
      package_facts:
        manager: auto
      register: package_facts_result
      ignore_errors: true


    - name: Backup Packager State after Change (Step 2)
      template:
        src: soft_facts.j2
        dest: "/opt/statebackup/software/deploy_pkg_single_grp_after_{{ ansible_date_time.date }}_{{ ansible_date_time.time }}_{{ inventory_hostname }}"
      delegate_to: localhost
      ignore_errors: true

