- name: Install Chelsio RPMs
  hosts: "{{ scanner }}"
  become: yes
  vars:
    major_version: 1
    minor_version: 0
    tick_version: 3
    logfile: "/var/rtt/log/test.{{ ansible_date_time.date }}.log"
    kernel_releases:
      - 3.10.0-1160.76.1.el7.x86_64
    centos_releases:
      - 7-9.2009.1.el7.centos-x86_64
    rpms_installing: CHELSIO_316

  tasks:
    - name: Create rtt user
      user:
        name: rtt
        state: present

    - name: Create log directory if it doesn't exist
      file:
        path: /var/rtt/log
        state: directory
        owner: rtt
        group: rtt
        mode: '0755'

    - name: Initialize log file
      delegate_to: "{{ groups[group_name][0] }}"
      copy:
        content: ""
        dest: "{{ logfile }}"
        owner: rtt
        group: rtt
        mode: '0644'

    - name: Append date to log file
      lineinfile:
        path: "{{ logfile }}"
        line: "{{ ansible_date_time.iso8601 }}"
        insertafter: EOF

    - name: Read RPM file contents
      delegate_to: localhost
      set_fact:
        rpm_file: "{{ lookup('file', '/opt/playbooks/rpm_lists/chelsio_rpm.txt') | replace('\r\n', ' ') | replace('\r', ' ') | replace('\n', ' ') }}"

    - name: Print the value of the fact
      debug:
        var: rpm_file

    - name: Install the required packages
      delegate_to: "{{ groups[group_name][0] }}"
      yum:
        name: "{{ rpm_file.split() }}"
        state: present
      when: rpm_file is defined and rpm_file | length > 0

    - name: Fail if RPM installation fails
      fail:
        msg: "RPM installation failed. See the logfile for more details."
      when: scanner is defined and group_name is defined and group_name in groups[scanner] and rpm_install_result.failed

    - name: Move shared object file
      shell: mv -v /usr/lib64/libibverbs/libcxgb4-rdmav22.so /usr/lib64/libibverbs/libcxgb4-rdmav22.so.hidden

