- name: Fetch facts from remote servers
  hosts: all
  gather_facts: true
  tasks:
    - name: Fetch facts
      template:
        src: facts_template.j2
        dest: "/opt/statebackup/facts/{{ ansible_date_time.date }}_{{ ansible_date_time.time }}_{{ inventory_hostname }}"
      delegate_to: localhost
    - name: Get package facts
      package_facts:
        manager: auto
      register: package_facts_result

    - name: Write package versions to file
      template:
        src: soft_facts.j2
        dest: "/opt/statebackup/software/{{ ansible_date_time.date }}_{{ ansible_date_time.time }}_{{ inventory_hostname }}"
      delegate_to: localhost