---
- name: Update packages in sync
  hosts: linux
  become: yes
  gather_facts: true
  tasks:
    - name: Update apt packages (for Debian-based systems)
      apt:
        upgrade: dist
        update_cache: yes
      when: ansible_pkg_mgr == 'apt'

    - name: Update yum packages (for Red Hat-based systems)
      yum:
        name: '*'
        state: latest
      when: ansible_pkg_mgr == 'yum'
